
import type { Plant } from '@/types';

export const initialPlants: Omit<Plant, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'tulsi',
    commonName: 'Tulsi (Holy Basil)',
    latinName: 'Ocimum sanctum',
    description: 'An aromatic perennial plant in the family Lamiaceae, native to the Indian subcontinent and widespread as a cultivated plant throughout the Southeast Asian tropics.',
    therapeuticUses: ['Immunity', 'Stress Relief', 'Respiratory Health'],
    region: 'Indian Subcontinent',
    classification: 'Lamiaceae / Ocimum',
    imageSrc: 'https://images.unsplash.com/photo-1596701193354-219b697d41f7?q=80&w=600&auto=format&fit=crop',
    imageHint: 'holy basil plant',
    ayushUses: 'Considered a sacred plant, Tulsi is used in Ayurveda to treat a variety of ailments including fever, cough, and to promote longevity.'
  },
  {
    id: 'ashwagandha',
    commonName: 'Ashwagandha',
    latinName: 'Withania somnifera',
    description: 'An evergreen shrub in the Solanaceae or nightshade family that grows in India, the Middle East, and parts of Africa.',
    therapeuticUses: ['Stress Relief', 'Cognitive Support', 'Adaptogen'],
    region: 'India, Middle East, Africa',
    classification: 'Solanaceae / Withania',
    imageSrc: 'https://bs.floristic.org/image/o/8a64d1f215d2e237418931795744465814594f71',
    imageHint: 'ashwagandha plant',
    ayushUses: 'Known as a potent adaptogen in Ayurveda, it helps the body manage stress and is used to boost brain function and lower blood sugar and cortisol levels.'
  },
  {
    id: 'turmeric',
    commonName: 'Turmeric',
    latinName: 'Curcuma longa',
    description: 'A flowering plant of the ginger family, Zingiberaceae, the roots of which are used in cooking.',
    therapeuticUses: ['Anti-inflammatory', 'Antioxidant', 'Digestive Health'],
    region: 'Southeast Asia',
    classification: 'Zingiberaceae / Curcuma',
    imageSrc: 'https://images.unsplash.com/photo-1582276558195-a63d91753948?q=80&w=600&auto=format&fit=crop',
    imageHint: 'turmeric root',
    ayushUses: 'Its active compound, curcumin, is a powerful anti-inflammatory and antioxidant. Used in Ayurveda for skin conditions, arthritis, and digestive issues.'
  },
  {
    id: 'brahmi',
    commonName: 'Brahmi',
    latinName: 'Bacopa monnieri',
    description: 'A perennial, creeping herb native to the wetlands of southern and Eastern India, Australia, Europe, Africa, Asia, and North and South America.',
    therapeuticUses: ['Cognitive Support', 'Memory Enhancement', 'Anti-anxiety'],
    region: 'Global wetlands',
    classification: 'Plantaginaceae / Bacopa',
    imageSrc: 'https://bs.floristic.org/image/o/8e04d493e8784d2dee77f62057639414598cf4d6',
    imageHint: 'bacopa monnieri plant',
    ayushUses: 'Often called a "brain tonic," Brahmi is used in Ayurvedic medicine to enhance memory, reduce anxiety, and treat epilepsy.'
  },
  {
    id: 'amla',
    commonName: 'Amla (Indian Gooseberry)',
    latinName: 'Phyllanthus emblica',
    description: 'A deciduous tree of the family Phyllanthaceae. It is known for its edible fruit of the same name.',
    therapeuticUses: ['Immunity', 'Vitamin C Source', 'Antioxidant'],
    region: 'India, Southeast Asia',
    classification: 'Phyllanthaceae / Phyllanthus',
    imageSrc: 'https://images.unsplash.com/photo-1623832386859-c29373ee9f29?q=80&w=600&auto=format&fit=crop',
    imageHint: 'amla fruit',
    ayushUses: 'A very rich source of Vitamin C, Amla is used to boost the immune system, improve skin and hair, and aid in digestion.'
  },
  {
    id: 'neem',
    commonName: 'Neem',
    latinName: 'Azadirachta indica',
    description: 'A tree in the mahogany family Meliaceae. It is one of two species in the genus Azadirachta, and is native to the Indian subcontinent.',
    therapeuticUses: ['Antibacterial', 'Skin Health', 'Dental Care'],
    region: 'Indian Subcontinent',
    classification: 'Meliaceae / Azadirachta',
    imageSrc: 'https://bs.floristic.org/image/o/8a93e3221e3f8b05634e9e02316e255a82898a12',
    imageHint: 'neem tree leaves',
    ayushUses: 'Known as "the village pharmacy," Neem has powerful antibacterial, antiviral, and antifungal properties, used for skin diseases, dental care, and as a blood purifier.'
  },
  {
    id: 'shatavari',
    commonName: 'Shatavari',
    latinName: 'Asparagus racemosus',
    description: 'A species of asparagus common throughout India and the Himalayas. It grows one to two metres tall and prefers to take root in gravelly, rocky soils high up in piedmont plains.',
    therapeuticUses: ['Hormonal Balance', 'Female Reproductive Health', 'Adaptogen'],
    region: 'India, Himalayas',
    classification: 'Asparagaceae / Asparagus',
    imageSrc: 'https://bs.floristic.org/image/o/070f80a4a89697a224647358e5d3c1a84c8a29a0',
    imageHint: 'asparagus racemosus plant',
    ayushUses: 'Primarily used as a female reproductive tonic, Shatavari supports hormonal balance, enhances libido, and is used to treat conditions like PCOS.'
  },
  {
    id: 'ginger',
    commonName: 'Ginger',
    latinName: 'Zingiber officinale',
    description: 'A flowering plant whose rhizome, ginger root or ginger, is widely used as a spice and a folk medicine.',
    therapeuticUses: ['Digestive Health', 'Anti-nausea', 'Anti-inflammatory'],
    region: 'Southeast Asia',
    classification: 'Zingiberaceae / Zingiber',
    imageSrc: 'https://images.unsplash.com/photo-1552318819-3c0049202671?q=80&w=600&auto=format&fit=crop',
    imageHint: 'ginger root spice',
    ayushUses: 'Used to aid digestion, reduce nausea, and help fight the flu and common cold. Its active ingredient, gingerol, has potent anti-inflammatory and antioxidant effects.'
  },
  {
    id: 'giloy',
    commonName: 'Giloy (Guduchi)',
    latinName: 'Tinospora cordifolia',
    description: 'A large, deciduous, extensively spreading, climbing shrub with several elongated twining branches.',
    therapeuticUses: ['Immunity', 'Fever Reducer', 'Detoxification'],
    region: 'Tropical India, Myanmar, Sri Lanka',
    classification: 'Menispermaceae / Tinospora',
    imageSrc: 'https://bs.floristic.org/image/o/f199e4ea8a82d25089f280e22b10313c8808169e',
    imageHint: 'giloy plant vine',
    ayushUses: 'Known as the "root of immortality," Giloy is a powerful immune-stimulant and is used in Ayurveda to treat chronic fever, diabetes, and high cholesterol.'
  },
  {
    id: 'moringa',
    commonName: 'Moringa',
    latinName: 'Moringa oleifera',
    description: 'A fast-growing, drought-resistant tree of the family Moringaceae, native to the Indian subcontinent.',
    therapeuticUses: ['Nutrient-rich', 'Antioxidant', 'Anti-inflammatory'],
    region: 'Indian Subcontinent',
    classification: 'Moringaceae / Moringa',
    imageSrc: 'https://images.unsplash.com/photo-1608832168993-2c908c691f3e?q=80&w=600&auto=format&fit=crop',
    imageHint: 'moringa leaves',
    ayushUses: 'Often called the "miracle tree," its leaves are a powerhouse of vitamins, minerals, and antioxidants. Used to combat malnutrition and reduce inflammation.'
  },
  {
    id: 'vetiver',
    commonName: 'Vetiver',
    latinName: 'Chrysopogon zizanioides',
    description: 'A perennial bunchgrass of the family Poaceae, native to India.',
    therapeuticUses: ['Cooling', 'Calming', 'Skin Health'],
    region: 'India',
    classification: 'Poaceae / Chrysopogon',
    imageSrc: 'https://bs.floristic.org/image/o/8e0bd6f272a2753a39e7c387b322a30b5015b699',
    imageHint: 'vetiver grass',
    ayushUses: 'Known as "the oil of tranquility," its essential oil is deeply calming and grounding. The roots are used for their cooling properties to treat heatstroke and inflammation.'
  },
  {
    id: 'sandalwood',
    commonName: 'Sandalwood',
    latinName: 'Santalum album',
    description: 'A class of woods from trees in the genus Santalum. The woods are heavy, yellow, and fine-grained, and, unlike many other aromatic woods, they retain their fragrance for decades.',
    therapeuticUses: ['Aromatic', 'Cooling', 'Antiseptic'],
    region: 'Southern India, Southeast Asia',
    classification: 'Santalaceae / Santalum',
    imageSrc: 'https://images.unsplash.com/photo-1622398934812-34335b29314?q=80&w=600&auto=format&fit=crop',
    imageHint: 'sandalwood powder',
    ayushUses: 'Highly prized for its cooling properties and fragrance. Used in Ayurveda for skin disorders, urinary tract infections, and as a meditative aid.'
  },
  {
    id: 'licorice',
    commonName: 'Licorice',
    latinName: 'Glycyrrhiza glabra',
    description: 'A herbaceous perennial legume native to Western Asia, North Africa, and Southern Europe.',
    therapeuticUses: ['Respiratory Health', 'Digestive Health', 'Adrenal Support'],
    region: 'Western Asia, North Africa, Southern Europe',
    classification: 'Fabaceae / Glycyrrhiza',
    imageSrc: 'https://images.unsplash.com/photo-1635398623049-53b708d5b88b?q=80&w=600&auto=format&fit=crop',
    imageHint: 'licorice root sticks',
    ayushUses: 'Used as a demulcent to soothe sore throats and ulcers. It also supports adrenal function and is a mild laxative.'
  },
  {
    id: 'peppermint',
    commonName: 'Peppermint',
    latinName: 'Mentha piperita',
    description: 'A hybrid mint, a cross between watermint and spearmint. Indigenous to Europe and the Middle East, the plant is now widespread in cultivation in many regions of the world.',
    therapeuticUses: ['Digestive Health', 'Headache Relief', 'Respiratory Aid'],
    region: 'Europe, Middle East',
    classification: 'Lamiaceae / Mentha',
    imageSrc: 'https://images.unsplash.com/photo-1596464555802-9599a41984a9?q=80&w=600&auto=format&fit=crop',
    imageHint: 'peppermint leaves',
    ayushUses: 'Commonly used to soothe digestive issues like IBS. The menthol in peppermint is a muscle relaxant and can help with tension headaches when applied topically.'
  },
  {
    id: 'lemongrass',
    commonName: 'Lemongrass',
    latinName: 'Cymbopogon citratus',
    description: 'A tall, perennial grass in the Poaceae grass family, native to maritime Southeast Asia.',
    therapeuticUses: ['Anxiety Relief', 'Antifungal', 'Digestive Aid'],
    region: 'Southeast Asia',
    classification: 'Poaceae / Cymbopogon',
    imageSrc: 'https://images.unsplash.com/photo-1594282486799-a4a35049b422?q=80&w=600&auto=format&fit=crop',
    imageHint: 'lemongrass stalks',
    ayushUses: 'Used in traditional medicine to relieve anxiety, lower cholesterol, and as a potent antibacterial and antifungal agent. Its oil is popular in aromatherapy.'
  },
  {
    id: 'chamomile',
    commonName: 'Chamomile',
    latinName: 'Matricaria chamomilla',
    description: 'A low-growing plant that has daisy-like flowers with a yellow center and white petals. Native to southern and eastern Europe.',
    therapeuticUses: ['Sleep Aid', 'Relaxant', 'Digestive Calm'],
    region: 'Europe, Western Asia',
    classification: 'Asteraceae / Matricaria',
    imageSrc: 'https://images.unsplash.com/photo-1563988187-84d3534d8a5c?q=80&w=600&auto=format&fit=crop',
    imageHint: 'chamomile flowers',
    ayushUses: 'Widely recognized for its calming properties. Chamomile tea is a popular remedy for insomnia and anxiety. It also helps soothe an upset stomach.'
  },
  {
    id: 'lavender',
    commonName: 'Lavender',
    latinName: 'Lavandula angustifolia',
    description: 'A flowering plant in the mint family, Lamiaceae. It is native to the Old World and is found from Cape Verde and the Canary Islands, Europe across to northern and eastern Africa, the Mediterranean, southwest Asia to southeast India.',
    therapeuticUses: ['Stress Relief', 'Sleep Aid', 'Antiseptic'],
    region: 'Mediterranean, Middle East, India',
    classification: 'Lamiaceae / Lavandula',
    imageSrc: 'https://images.unsplash.com/photo-1565015626359-a21235b29314?q=80&w=600&auto=format&fit=crop',
    imageHint: 'lavender fields',
    ayushUses: 'The essential oil is renowned for its ability to reduce stress, anxiety, and promote sleep. It also has antiseptic and anti-inflammatory properties, useful for skin irritations.'
  },
  {
    id: 'rosemary',
    commonName: 'Rosemary',
    latinName: 'Salvia rosmarinus',
    description: 'A woody, perennial herb with fragrant, evergreen, needle-like leaves and white, pink, purple, or blue flowers, native to the Mediterranean region.',
    therapeuticUses: ['Cognitive Support', 'Antioxidant', 'Circulation'],
    region: 'Mediterranean',
    classification: 'Lamiaceae / Salvia',
    imageSrc: 'https://images.unsplash.com/photo-1597855145993-03a305141b71?q=80&w=600&auto=format&fit=crop',
    imageHint: 'rosemary sprig',
    ayushUses: 'Traditionally used to improve memory and concentration. Its aroma can be invigorating, and it is a rich source of antioxidants that boost the immune system.'
  },
  {
    id: 'echinacea',
    commonName: 'Echinacea',
    latinName: 'Echinacea purpurea',
    description: 'Also known as the purple coneflower, it is a North American species of flowering plant in the sunflower family.',
    therapeuticUses: ['Immune Support', 'Cold & Flu', 'Anti-inflammatory'],
    region: 'North America',
    classification: 'Asteraceae / Echinacea',
    imageSrc: 'https://images.unsplash.com/photo-1600862082260-23ac7547d79b?q=80&w=600&auto=format&fit=crop',
    imageHint: 'purple coneflower',
    ayushUses: 'Popularly used to shorten the duration of the common cold and flu and reduce symptoms, such as sore throat, cough, and fever.'
  },
  {
    id: 'marshmallow-root',
    commonName: 'Marshmallow Root',
    latinName: 'Althaea officinalis',
    description: 'A perennial species indigenous to Europe, Western Asia, and North Africa, which is used in herbalism and as an ornamental plant.',
    therapeuticUses: ['Sore Throat', 'Digestive Health', 'Skin Irritation'],
    region: 'Europe, Western Asia, North Africa',
    classification: 'Malvaceae / Althaea',
    imageSrc: 'https://bs.floristic.org/image/o/8f3994348a27d53b9a527f3118a1a473f7663f73',
    imageHint: 'marshmallow plant flower',
    ayushUses: 'Its high mucilage content makes it a useful demulcent, soothing irritated membranes of the respiratory and digestive tracts.'
  }
];
