// IMPORTANT: This file is the source of truth for all plant-related data in the application
// when a database connection is not available.

import type { Plant } from '@/types';

// This data is used as a fallback if the Firestore database is empty or not configured.
export const initialPlants: Plant[] = [
  {
    id: 'tulsi',
    commonName: 'Tulsi',
    latinName: 'Ocimum tenuiflorum',
    description: 'Known as Holy Basil, Tulsi is revered in Ayurveda for its medicinal and spiritual properties. It is an adaptogen that helps the body manage stress.',
    therapeuticUses: ['Stress Relief', 'Immunity', 'Respiratory Health'],
    region: 'Native to the Indian subcontinent',
    classification: 'Lamiaceae / Ocimum',
    imageSrc: 'https://bs.floristic.org/image/o/8a9609439c2e0439999a224f8d558b3e51a707b1',
    imageHint: 'tulsi plant',
    ayushUses: 'Used in Ayurveda for treating coughs, colds, and improving longevity. It is considered a sacred plant in Hinduism.',
    source: 'local',
  },
  {
    id: 'brahmi',
    commonName: 'Brahmi',
    latinName: 'Bacopa monnieri',
    description: 'A staple in traditional Ayurvedic medicine, Brahmi is a powerful herb acclaimed for its memory-enhancing properties and its ability to support cognitive function.',
    therapeuticUses: ['Cognitive Enhancement', 'Anxiety Relief', 'Anti-inflammatory'],
    region: 'Wetlands of southern and Eastern India, Australia, Europe, Africa, Asia, and North and South America',
    classification: 'Plantaginaceae / Bacopa',
    imageSrc: 'https://bs.floristic.org/image/o/8e7f2438596005b8109d780355153213c9053995',
    imageHint: 'brahmi leaves',
    ayushUses: 'Used as a brain tonic (Medhya Rasayana) to improve memory, intelligence, and concentration. Also used for anxiety and epilepsy.',
    source: 'local',
  },
  {
    id: 'turmeric',
    commonName: 'Turmeric',
    latinName: 'Curcuma longa',
    description: 'A bright yellow spice from the ginger family, Turmeric contains curcumin, a compound with potent anti-inflammatory and antioxidant properties.',
    therapeuticUses: ['Anti-inflammatory', 'Digestive Health', 'Antioxidant'],
    region: 'Native to Southeast Asia',
    classification: 'Zingiberaceae / Curcuma',
    imageSrc: 'https://bs.floristic.org/image/o/262a19f2a9d6a36a7d65b1b4edc493c4e3650058',
    imageHint: 'turmeric root',
    ayushUses: 'Widely used in Ayurveda and Siddha medicine as an anti-inflammatory agent for conditions like arthritis, as well as for digestive and skin issues.',
    source: 'local',
  },
  {
    id: 'ashwagandha',
    commonName: 'Ashwagandha',
    latinName: 'Withania somnifera',
    description: 'Known as "Indian Ginseng," Ashwagandha is an adaptogenic herb that helps reduce stress and anxiety while improving strength and vitality.',
    therapeuticUses: ['Stress Relief', 'Vitality', 'Cognitive Enhancement'],
    region: 'Native to India and North Africa',
    classification: 'Solanaceae / Withania',
    imageSrc: 'https://bs.floristic.org/image/o/9f8d4e5f7a6a4f1a2b3c4d5e6f7g8h9i0j1k2l3m',
    imageHint: 'ashwagandha plant',
    ayushUses: 'A cornerstone of Ayurvedic medicine, used to reduce stress, improve strength, and enhance cognitive function. It is considered a Rasayana (rejuvenator).',
    source: 'local',
  },
  {
    id: 'neem',
    commonName: 'Neem',
    latinName: 'Azadirachta indica',
    description: 'A versatile tree whose leaves, bark, and seeds are used for their powerful antibacterial, antifungal, and antiviral properties.',
    therapeuticUses: ['Antibacterial', 'Skin Health', 'Dental Care'],
    region: 'Native to the Indian subcontinent',
    classification: 'Meliaceae / Azadirachta',
    imageSrc: 'https://bs.floristic.org/image/o/07e9d729a287a2a7f5c7a52f8a846b088360d5b7',
    imageHint: 'neem leaves',
    ayushUses: 'Known as the "village pharmacy," its parts are used in Unani and Ayurvedic medicine for skin diseases, dental care, and as a blood purifier.',
    source: 'local',
  },
  {
    id: 'amla',
    commonName: 'Amla',
    latinName: 'Phyllanthus emblica',
    description: 'Indian Gooseberry, or Amla, is one of the richest natural sources of Vitamin C and is a potent antioxidant that supports overall health.',
    therapeuticUses: ['Immunity', 'Digestive Health', 'Antioxidant'],
    region: 'Native to India',
    classification: 'Phyllanthaceae / Phyllanthus',
    imageSrc: 'https://bs.floristic.org/image/o/814e4277c683b5b136894b59146193798555e09f',
    imageHint: 'amla fruit',
    ayushUses: 'A key ingredient in Chyawanprash, used in Ayurveda to boost immunity, aid digestion, and promote healthy aging.',
    source: 'local',
  },
  {
    id: 'giloy',
    commonName: 'Giloy',
    latinName: 'Tinospora cordifolia',
    description: 'Known as "Amrita" or the root of immortality, Giloy is a climbing shrub praised in Ayurveda for its ability to boost immunity and fight fevers.',
    therapeuticUses: ['Immunity', 'Fever Reducer', 'Detoxification'],
    region: 'Tropical regions of the Indian subcontinent',
    classification: 'Menispermaceae / Tinospora',
    imageSrc: 'https://bs.floristic.org/image/o/c31f1f2e6b2d6e3c1b7a2e4f6g8h0i2k4m6n8o0',
    imageHint: 'giloy vine',
    ayushUses: 'Used to treat chronic fevers, manage diabetes, and boost the immune system. Its stem is most commonly used.',
    source: 'local',
  },
  {
    id: 'moringa',
    commonName: 'Moringa',
    latinName: 'Moringa oleifera',
    description: 'Often called the "miracle tree," its leaves are packed with an incredible amount of nutrients, including vitamins, minerals, and proteins.',
    therapeuticUses: ['Nutrition', 'Antioxidant', 'Anti-inflammatory'],
    region: 'Native to the Himalayan foothills',
    classification: 'Moringaceae / Moringa',
    imageSrc: 'https://bs.floristic.org/image/o/5a7d3a8e9f0b1c2d3e4f5g6h7i8j9k0l1m2n3',
    imageHint: 'moringa leaves',
    ayushUses: 'Used in Siddha medicine to treat a wide range of ailments due to its high nutritional content. It is considered a superfood.',
    source: 'local',
  },
];
