import type { Plant, TourCategory, QuizQuestion } from '@/types';
import { Leaf, ShieldHalf, Activity, Brain, Users, Sparkles, Filter, Wind, Sun, HeartPulse, Soup } from 'lucide-react';

export const plants: Plant[] = [
  {
    id: 'tulsi',
    commonName: 'Tulsi (Holy Basil)',
    latinName: 'Ocimum tenuiflorum',
    description: 'Tulsi is a sacred plant in Hindu belief. It is revered for its medicinal properties and is often grown in courtyards of Hindu houses.',
    therapeuticUses: ['Immunity Booster', 'Stress Relief', 'Respiratory Health'],
    region: 'Indian Subcontinent',
    classification: 'Herb',
    imageSrc: 'https://images.unsplash.com/photo-1622588343888-4390b3967a55?q=80&w=600&auto=format&fit=crop',
    imageHint: 'tulsi plant',
    videoSrc: 'https://www.w3schools.com/html/mov_bbb.mp4', // Placeholder video
    ayushUses: 'Widely used in Ayurveda for treating coughs, colds, and improving longevity. Considered an adaptogen.',
  },
  {
    id: 'ashwagandha',
    commonName: 'Ashwagandha (Indian Ginseng)',
    latinName: 'Withania somnifera',
    description: 'Ashwagandha is a prominent herb in Ayurvedic medicine known for its adaptogenic properties, helping the body manage stress.',
    therapeuticUses: ['Stress Relief', 'Energy Booster', 'Cognitive Function'],
    region: 'India, Middle East, Africa',
    classification: 'Shrub',
    imageSrc: 'https://images.unsplash.com/photo-1630615501848-c1e0996bcb65?q=80&w=600&auto=format&fit=crop',
    imageHint: 'ashwagandha root',
    ayushUses: 'Used in Ayurveda to reduce stress and anxiety, improve energy levels, and enhance cognitive function. Its roots are primarily used.',
  },
  {
    id: 'turmeric',
    commonName: 'Turmeric (Haldi)',
    latinName: 'Curcuma longa',
    description: 'Turmeric is a bright yellow spice derived from the rhizome of the Curcuma longa plant. It has been used for centuries in cooking and medicine.',
    therapeuticUses: ['Anti-inflammatory', 'Antioxidant', 'Digestive Health'],
    region: 'Southeast Asia',
    classification: 'Rhizome',
    imageSrc: 'https://images.unsplash.com/photo-1588138402284-52f4315126d4?q=80&w=600&auto=format&fit=crop',
    imageHint: 'turmeric spice',
    videoSrc: 'https://www.w3schools.com/html/mov_bbb.mp4', // Placeholder video
    ayushUses: 'A staple in Ayurvedic medicine for its anti-inflammatory properties, used to treat a variety of conditions including arthritis and digestive issues.',
  },
  {
    id: 'neem',
    commonName: 'Neem',
    latinName: 'Azadirachta indica',
    description: 'Neem is a fast-growing tree known for its bitter taste and wide range of medicinal applications, from skincare to pest control.',
    therapeuticUses: ['Skin Health', 'Anti-bacterial', 'Dental Care'],
    region: 'Indian Subcontinent',
    classification: 'Tree',
    imageSrc: 'https://images.unsplash.com/photo-1593361189476-c56a84f3316f?q=80&w=600&auto=format&fit=crop',
    imageHint: 'neem leaves',
    ayushUses: 'Used in Ayurveda for its purifying properties. Effective for skin diseases, dental health, and as a blood purifier.',
  },
  {
    id: 'brahmi',
    commonName: 'Brahmi (Water Hyssop)',
    latinName: 'Bacopa monnieri',
    description: 'Brahmi is a staple in traditional Ayurvedic medicine, often used to enhance memory and cognitive functions.',
    therapeuticUses: ['Cognitive Function', 'Stress Relief', 'Anti-anxiety'],
    region: 'Wetlands in Asia, Australia, Europe, Africa, Americas',
    classification: 'Herb',
    imageSrc: 'https://images.unsplash.com/photo-1628185188439-011593465b45?q=80&w=600&auto=format&fit=crop',
    imageHint: 'brahmi plant',
    ayushUses: 'Known as a brain tonic in Ayurveda, it supports memory, learning, and concentration. Also used to calm the nerves.',
  },
  {
    id: 'amla',
    commonName: 'Amla (Indian Gooseberry)',
    latinName: 'Phyllanthus emblica',
    description: 'Amla is a small, green fruit renowned for its extremely high vitamin C content and potent antioxidant properties.',
    therapeuticUses: ['Immunity Booster', 'Antioxidant', 'Hair Health'],
    region: 'India and Southeast Asia',
    classification: 'Fruit Tree',
    imageSrc: 'https://images.unsplash.com/photo-1623351988118-4716441b0042?q=80&w=600&auto=format&fit=crop',
    imageHint: 'amla fruit',
    ayushUses: 'A cornerstone of Ayurvedic medicine, used in preparations like Chyawanprash to rejuvenate the body, boost immunity, and improve hair and skin.',
  },
  {
    id: 'ginger',
    commonName: 'Ginger (Adrak)',
    latinName: 'Zingiber officinale',
    description: 'Ginger is a flowering plant whose rhizome, ginger root, is widely used as a spice and a folk medicine.',
    therapeuticUses: ['Digestive Health', 'Anti-inflammatory', 'Nausea Relief'],
    region: 'Southeast Asia',
    classification: 'Rhizome',
    imageSrc: 'https://images.unsplash.com/photo-1627888639591-f95b799a4c03?q=80&w=600&auto=format&fit=crop',
    imageHint: 'ginger root',
    ayushUses: 'In Ayurveda, ginger is known as a universal medicine. It is used to aid digestion, reduce inflammation, and treat colds and nausea.',
  },
];

export const tourCategories: TourCategory[] = [
  {
    id: 'immunity-boosters',
    name: 'Immunity Boosters',
    description: 'Explore plants renowned for strengthening the immune system.',
    icon: ShieldHalf,
    plantIds: ['tulsi', 'ashwagandha', 'turmeric', 'amla'],
    imageSrc: 'https://images.unsplash.com/photo-1579113800035-7a0342a43f11?q=80&w=400&auto=format&fit=crop',
    imageHint: 'immune system'
  },
  {
    id: 'stress-relief',
    name: 'Stress Relief',
    description: 'Discover herbs that help calm the mind and reduce stress.',
    icon: Activity,
    plantIds: ['tulsi', 'ashwagandha', 'brahmi'],
    imageSrc: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=400&auto=format&fit=crop',
    imageHint: 'calm meditation'
  },
  {
    id: 'cognitive-enhancers',
    name: 'Cognitive Enhancers',
    description: 'Learn about plants that support brain health and cognitive function.',
    icon: Brain,
    plantIds: ['ashwagandha', 'brahmi'],
    imageSrc: 'https://images.unsplash.com/photo-1531592618329-9e8753235338?q=80&w=400&auto=format&fit=crop',
    imageHint: 'brain function'
  },
  {
    id: 'digestive-health',
    name: 'Digestive Health',
    description: 'Find plants that aid digestion and soothe the stomach.',
    icon: Soup,
    plantIds: ['turmeric', 'ginger'],
    imageSrc: 'https://images.unsplash.com/photo-1544558000-85c8a41755da?q=80&w=400&auto=format&fit=crop',
    imageHint: 'herbal tea'
  },
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Which plant is commonly known as "Holy Basil"?',
    options: ['Ashwagandha', 'Tulsi', 'Neem', 'Turmeric'],
    correctAnswer: 'Tulsi',
    plantId: 'tulsi',
  },
  {
    id: 'q2',
    question: 'What is the primary therapeutic use of Ashwagandha?',
    options: ['Digestive Health', 'Skin Care', 'Stress Relief', 'Respiratory Health'],
    correctAnswer: 'Stress Relief',
    plantId: 'ashwagandha',
  },
  {
    id: 'q3',
    question: 'Curcuma longa is the Latin name for which spice?',
    options: ['Ginger', 'Cinnamon', 'Cardamom', 'Turmeric'],
    correctAnswer: 'Turmeric',
    plantId: 'turmeric',
  },
  {
    id: 'q4',
    question: 'Which of these plants is known for its purifying properties for skin and dental health?',
    options: ['Brahmi', 'Neem', 'Tulsi', 'Amla'],
    correctAnswer: 'Neem',
    plantId: 'neem',
  },
  {
    id: 'q5',
    question: 'Brahmi is well-known in Ayurveda for enhancing:',
    options: ['Physical Strength', 'Immune Response', 'Cognitive Function', 'Digestive Speed'],
    correctAnswer: 'Cognitive Function',
    plantId: 'brahmi',
  },
  {
    id: 'q6',
    question: 'Which fruit is a very potent source of Vitamin C and used in Chyawanprash?',
    options: ['Ginger', 'Amla', 'Neem', 'Brahmi'],
    correctAnswer: 'Amla',
    plantId: 'amla',
  },
  {
    id: 'q7',
    question: 'Which rhizome is famous for aiding digestion and relieving nausea?',
    options: ['Turmeric', 'Ashwagandha', 'Ginger', 'Tulsi'],
    correctAnswer: 'Ginger',
    plantId: 'ginger',
  },
];
