
// IMPORTANT: This file is the source of truth for all plant-related data in the application.
// When moving to a database, this data would be migrated.

import type { Plant, TourCategory, QuizQuestion } from '@/types';
import { Leaf, ShieldHalf, Activity, Brain, Users, Sparkles, Filter, Wind, Sun, HeartPulse, Soup } from 'lucide-react';

// We keep this static data here because Lucide icons (functions) cannot be stored in Firestore.
// The tour data will be fetched from Firestore, and then the icon will be mapped from this list.
export const tourCategories: TourCategory[] = [
  {
    id: 'immunity-boosters',
    name: 'Immunity Boosters',
    description: 'Explore plants renowned for strengthening the immune system.',
    icon: ShieldHalf,
    plantIds: ['tulsi', 'amla', 'giloy', 'moringa', 'turmeric', 'ginger', 'echinacea', 'elderberry'],
    imageSrc: 'https://images.unsplash.com/photo-1579113800035-7a0342a43f11?q=80&w=400&auto=format&fit=crop',
    imageHint: 'immune system'
  },
  {
    id: 'stress-relief',
    name: 'Stress Relief',
    description: 'Discover herbs that help calm the mind and reduce stress.',
    icon: Activity,
    plantIds: ['tulsi', 'ashwagandha', 'brahmi', 'vetiver', 'sandalwood', 'lemongrass', 'lavender', 'chamomile'],
    imageSrc: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=400&auto=format&fit=crop',
    imageHint: 'calm meditation'
  },
  {
    id: 'cognitive-enhancers',
    name: 'Cognitive Enhancers',
    description: 'Learn about plants that support brain health and cognitive function.',
    icon: Brain,
    plantIds: ['ashwagandha', 'brahmi', 'gotu-kola', 'ginkgo-biloba', 'rosemary'],
    imageSrc: 'https://images.unsplash.com/photo-1531592618329-9e8753235338?q=80&w=400&auto=format&fit=crop',
    imageHint: 'brain function'
  },
  {
    id: 'digestive-health',
    name: 'Digestive Health',
    description: 'Find plants that aid digestion and soothe the stomach.',
    icon: Soup,
    plantIds: ['turmeric', 'ginger', 'licorice', 'peppermint', 'fennel', 'cardamom', 'marshmallow-root'],
    imageSrc: 'https://images.unsplash.com/photo-1544558000-85c8a41755da?q=80&w=400&auto=format&fit=crop',
    imageHint: 'herbal tea'
  },
];


export const plants: Plant[] = [
  {
    id: 'tulsi',
    commonName: 'Tulsi (Holy Basil)',
    latinName: 'Ocimum tenuiflorum',
    description: 'Tulsi is a sacred plant in Hindu belief. It is considered an "elixir of life" in Ayurveda for its wide range of health benefits.',
    therapeuticUses: ['Immunity Booster', 'Stress Relief', 'Respiratory Health'],
    region: 'Indian Subcontinent',
    classification: 'Lamiaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1604148485233-024b4c648012?q=80&w=600&auto=format&fit=crop',
    ayushUses: 'Widely used in Ayurveda for treating coughs, colds, and as an adaptogen to help the body resist stress. Also used in religious ceremonies.',
  },
  {
    id: 'ashwagandha',
    commonName: 'Ashwagandha',
    latinName: 'Withania somnifera',
    description: 'Known as "Indian Ginseng," Ashwagandha is a powerful adaptogen used for centuries to relieve stress, increase energy levels, and improve concentration.',
    therapeuticUses: ['Adaptogen', 'Stress Relief', 'Cognitive Function'],
    region: 'India, Middle East, and parts of Africa',
    classification: 'Nightshade family',
    imageSrc: 'https://images.unsplash.com/photo-1628102322359-993427a13b94?q=80&w=600&auto=format&fit=crop',
    imageHint: 'ashwagandha root powder',
    ayushUses: 'A cornerstone of Ayurvedic medicine, prescribed for anxiety, fatigue, and to boost vitality. It is considered a Rasayana (rejuvenator).',
  },
  {
    id: 'turmeric',
    commonName: 'Turmeric',
    latinName: 'Curcuma longa',
    description: 'A bright yellow spice from the ginger family, turmeric is celebrated for its potent anti-inflammatory properties, primarily due to its active compound, curcumin.',
    therapeuticUses: ['Anti-inflammatory', 'Antioxidant', 'Digestive Health'],
    region: 'Southeast Asia',
    classification: 'Ginger family',
    imageSrc: 'https://images.unsplash.com/photo-1582235334203-a33734065e82?q=80&w=600&auto=format&fit=crop',
    imageHint: 'turmeric root spice',
    ayushUses: 'Used in Ayurveda and Siddha medicine as a cleansing agent, for digestive disorders, and to treat skin conditions. Also a key ingredient in Indian cuisine.',
  },
  {
    id: 'brahmi',
    commonName: 'Brahmi',
    latinName: 'Bacopa monnieri',
    description: 'A staple in traditional Ayurvedic medicine, Brahmi is a powerful nootropic herb used to enhance memory, reduce anxiety, and support overall brain function.',
    therapeuticUses: ['Memory Enhancer', 'Cognitive Function', 'Stress Relief'],
    region: 'Wetlands of Southern and Eastern India, Australia, Europe, Africa, Asia, and North and South America',
    classification: 'Plantaginaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1599134842168-36c533e43343?q=80&w=600&auto=format&fit=crop',
    imageHint: 'green herb water',
    ayushUses: 'Known as a "brain tonic" in Ayurveda. Used to improve intelligence, memory, and treat conditions like epilepsy and insomnia.',
  },
  {
    id: 'amla',
    commonName: 'Amla (Indian Gooseberry)',
    latinName: 'Phyllanthus emblica',
    description: 'Amla is one of the richest natural sources of Vitamin C. It is a potent antioxidant that helps boost the immune system and delay aging.',
    therapeuticUses: ['Immunity Booster', 'Antioxidant', 'Hair Health'],
    region: 'India and Southeast Asia',
    classification: 'Phyllanthaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1624453449377-6b4d45084124?q=80&w=600&auto=format&fit=crop',
    imageHint: 'amla fruit',
    ayushUses: 'A key ingredient in many Ayurvedic formulations, including Chyawanprash. Used to enhance digestion, treat constipation, and promote longevity.',
  },
  {
    id: 'giloy',
    commonName: 'Giloy (Guduchi)',
    latinName: 'Tinospora cordifolia',
    description: 'Giloy is a climbing shrub known in Ayurveda as the "root of immortality" for its powerful healing and immunomodulatory properties.',
    therapeuticUses: ['Immunity Booster', 'Fever Reducer', 'Detoxification'],
    region: 'Tropical regions of the Indian subcontinent',
    classification: 'Menispermaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1605515256244-a276b5e0034a?q=80&w=600&auto=format&fit=crop',
    imageHint: 'heart shaped leaves',
    ayushUses: 'Highly revered in Ayurveda for its ability to treat chronic fevers, manage diabetes, and boost the immune system. It\'s considered a Tridoshic herb.',
  },
  {
    id: 'moringa',
    commonName: 'Moringa',
    latinName: 'Moringa oleifera',
    description: 'Often called the "drumstick tree" or "miracle tree," Moringa is packed with vitamins, minerals, and proteins, making it a powerful superfood.',
    therapeuticUses: ['Nutrient-Rich', 'Antioxidant', 'Anti-inflammatory'],
    region: 'Himalayan foothills of India',
    classification: 'Moringaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1609503463124-af84a43c2227?q=80&w=600&auto=format&fit=crop',
    imageHint: 'moringa leaves',
    ayushUses: 'Used in Siddha medicine for its high nutritional content. Almost all parts of the plant are used for treating various ailments, from malnutrition to inflammation.',
  },
  {
    id: 'ginger',
    commonName: 'Ginger',
    latinName: 'Zingiber officinale',
    description: 'A flowering plant whose rhizome, ginger root, is widely used as a spice and a folk medicine. It is known for its ability to soothe an upset stomach.',
    therapeuticUses: ['Digestive Health', 'Anti-nausea', 'Anti-inflammatory'],
    region: 'Southeast Asia',
    classification: 'Zingiberaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1582883397943-7b74684497a6?q=80&w=600&auto=format&fit=crop',
    imageHint: 'ginger root',
    ayushUses: 'A universal medicine in Ayurveda, used as a digestive aid, to treat colds and coughs, and to reduce inflammation. It is known as "vishwabhesaj" (the universal remedy).',
  },
  {
    id: 'licorice',
    commonName: 'Licorice',
    latinName: 'Glycyrrhiza glabra',
    description: 'The root of this plant is known for its sweet flavor and is used to treat sore throats, coughs, and digestive issues.',
    therapeuticUses: ['Sore Throat Relief', 'Digestive Health', 'Respiratory Health'],
    region: 'Western Asia and Southern Europe',
    classification: 'Fabaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1615485921782-44161f3645e5?q=80&w=600&auto=format&fit=crop',
    imageHint: 'licorice root sticks',
    ayushUses: 'Called "Yashtimadhu" in Ayurveda, it is used as a gentle expectorant, for soothing ulcers, and as a harmonizing agent in herbal formulas.',
  },
  {
    id: 'peppermint',
    commonName: 'Peppermint',
    latinName: 'Mentha piperita',
    description: 'A hybrid mint, a cross between watermint and spearmint. It has a high menthol content and is often used for its cooling sensation and to aid digestion.',
    therapeuticUses: ['Digestive Health', 'Headache Relief', 'Cooling Agent'],
    region: 'Europe and Middle East',
    classification: 'Lamiaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1597855018429-436f56191c7a?q=80&w=600&auto=format&fit=crop',
    imageHint: 'peppermint leaves',
    ayushUses: 'Used in Unani and other traditional systems to treat indigestion, flatulence, and as a flavoring agent. Its essential oil is used for aromatherapy.',
  },
  {
    id: 'sandalwood',
    commonName: 'Sandalwood',
    latinName: 'Santalum album',
    description: 'A class of woods from trees in the genus Santalum, prized for their distinctive fragrance. The oil is used in perfumes, cosmetics, and sacred unguents.',
    therapeuticUses: ['Aromatherapy', 'Skin Care', 'Cooling Agent'],
    region: 'Southern India and Southeast Asia',
    classification: 'Santalaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1622396939885-3c1a3d3c8b41?q=80&w=600&auto=format&fit=crop',
    imageHint: 'sandalwood powder incense',
    ayushUses: 'In Ayurveda, "Chandan" is used for its cooling properties, to treat skin conditions like acne and rashes, and in meditation for its calming aroma.',
  },
  {
    id: 'vetiver',
    commonName: 'Vetiver',
    latinName: 'Chrysopogon zizanioides',
    description: 'A perennial bunchgrass of the family Poaceae, whose roots have a rich, earthy, and grounding fragrance. The essential oil is known as the "oil of tranquility".',
    therapeuticUses: ['Grounding', 'Cooling Agent', 'Stress Relief'],
    region: 'India',
    classification: 'Poaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1618332158552-3843f1b4028f?q=80&w=600&auto=format&fit=crop',
    imageHint: 'dried grass roots',
    ayushUses: 'Known as "Khus" in Ayurveda, it is used to cool the body, relieve thirst, and calm the mind. It is also woven into mats and curtains for its cooling effect.',
  },
  {
    id: 'lemongrass',
    commonName: 'Lemongrass',
    latinName: 'Cymbopogon citratus',
    description: 'A tall, stalky plant with a fresh, lemony aroma and a citrus flavor. It is a common ingredient in Asian cooking and is also used for medicinal purposes.',
    therapeuticUses: ['Digestive Health', 'Fever Reducer', 'Aromatherapy'],
    region: 'Tropical Asia',
    classification: 'Poaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1596225464169-d69c7333de49?q=80&w=600&auto=format&fit=crop',
    imageHint: 'lemongrass stalks',
    ayushUses: 'Used in traditional medicine to treat digestive issues, fevers, and nervous disorders. The oil is used to relieve muscle pain.',
  },
  {
    id: 'fennel',
    commonName: 'Fennel',
    latinName: 'Foeniculum vulgare',
    description: 'A flowering plant species in the carrot family. It is a hardy, perennial herb with yellow flowers and feathery leaves, and has a mild licorice-like flavor.',
    therapeuticUses: ['Digestive Health', 'Anti-gas', 'Breath Freshener'],
    region: 'Mediterranean',
    classification: 'Apiaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1586361323388-75c8725f756d?q=80&w=600&auto=format&fit=crop',
    imageHint: 'fennel seeds',
    ayushUses: 'Known as "Saunf" in India, it is widely used as a mouth freshener and digestive aid after meals. It helps relieve gas and indigestion.',
  },
  {
    id: 'cardamom',
    commonName: 'Cardamom',
    latinName: 'Elettaria cardamomum',
    description: 'Known as the "Queen of Spices," cardamom has a strong, unique taste, with an intensely aromatic fragrance. It is used in both sweet and savory dishes.',
    therapeuticUses: ['Digestive Health', 'Diuretic', 'Breath Freshener'],
    region: 'Indian subcontinent',
    classification: 'Ginger family',
    imageSrc: 'https://images.unsplash.com/photo-1559819239-1a0a21a98e21?q=80&w=600&auto=format&fit=crop',
    imageHint: 'cardamom pods',
    ayushUses: 'In Ayurveda, it is used to treat digestive problems, respiratory issues like asthma, and bad breath. It is considered to be Tridoshic.',
  },
  {
    id: 'gotu-kola',
    commonName: 'Gotu Kola',
    latinName: 'Centella asiatica',
    description: 'Referred to as the "herb of longevity," Gotu Kola is a staple in traditional Chinese, Indonesian, and Ayurvedic medicine, known for boosting brainpower.',
    therapeuticUses: ['Cognitive Function', 'Skin Health', 'Nervine Tonic'],
    region: 'Wetlands in Asia',
    classification: 'Apiaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1628108107937-67995f3b3d5c?q=80&w=600&auto=format&fit=crop',
    imageHint: 'gotu kola leaves',
    ayushUses: 'Often confused with Brahmi, Mandukaparni (Gotu Kola) is revered in Ayurveda for enhancing cognitive function, promoting wound healing, and revitalizing nerves.',
  },
  {
    id: 'neem',
    commonName: 'Neem',
    latinName: 'Azadirachta indica',
    description: 'Known as the "village pharmacy," every part of the neem tree has been used in traditional medicine for its antibacterial, antifungal, and antiviral properties.',
    therapeuticUses: ['Antibacterial', 'Skin Health', 'Blood Purifier'],
    region: 'Indian subcontinent',
    classification: 'Meliaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1615485922359-9d8f615f22ca?q=80&w=600&auto=format&fit=crop',
    imageHint: 'neem leaves',
    ayushUses: 'A powerful blood purifier and detoxifier in Ayurveda. Used to treat a vast range of skin diseases, dental problems, and as a potent insect repellent.',
  },
  {
    id: 'shatavari',
    commonName: 'Shatavari',
    latinName: 'Asparagus racemosus',
    description: 'Considered the foremost herb for female health in Ayurveda. Its name translates to "she who possesses a hundred husbands," referring to its rejuvenating effects.',
    therapeuticUses: ['Female Reproductive Health', 'Adaptogen', 'Digestive Health'],
    region: 'Himalayas, India, and Nepal',
    classification: 'Asparagaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1556910110-a5a636e13385?q=80&w=600&auto=format&fit=crop&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'asparagus root powder',
    ayushUses: 'The primary rejuvenative tonic for females in Ayurveda. It supports lactation, balances hormones, and soothes the digestive tract.',
  },
  {
    id: 'ginkgo-biloba',
    commonName: 'Ginkgo Biloba',
    latinName: 'Ginkgo biloba',
    description: 'One of the oldest living tree species, ginkgo extract is collected from the dried green leaves and is popular for its ability to improve blood flow to the brain.',
    therapeuticUses: ['Cognitive Function', 'Circulation', 'Eye Health'],
    region: 'China',
    classification: 'Ginkgophyta',
    imageSrc: 'https://images.unsplash.com/photo-1615486518177-3a137ce52882?q=80&w=600&auto=format&fit=crop',
    imageHint: 'ginkgo biloba leaves',
    ayushUses: 'While not traditionally a part of AYUSH, it is now widely recognized and used in modern herbalism for similar purposes as Brahmi—to enhance memory and circulation.',
  },
  {
    id: 'eucalyptus',
    commonName: 'Eucalyptus',
    latinName: 'Eucalyptus globulus',
    description: 'Native to Australia, the oil from the eucalyptus tree is a common ingredient in chest rubs and cold remedies, known for its ability to clear congestion.',
    therapeuticUses: ['Respiratory Health', 'Decongestant', 'Antiseptic'],
    region: 'Australia',
    classification: 'Myrtaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1549616174-8c46419b02a9?q=80&w=600&auto=format&fit=crop',
    imageHint: 'eucalyptus leaves',
    ayushUses: 'Used in Siddha medicine and modern aromatherapy as an inhalant to treat colds and bronchitis. Its cooling properties also help with muscle aches.',
  },
  {
    id: 'lavender',
    commonName: 'Lavender',
    latinName: 'Lavandula angustifolia',
    description: 'A popular herb known for its calming scent, lavender is used in aromatherapy to reduce stress and anxiety, and promote restful sleep.',
    therapeuticUses: ['Stress Relief', 'Sleep Aid', 'Aromatherapy'],
    region: 'Mediterranean, Middle East, and India',
    classification: 'Mint family',
    imageSrc: 'https://images.unsplash.com/photo-1565015626376-bf0da7def242?q=80&w=600&auto=format&fit=crop',
    imageHint: 'lavender fields',
    ayushUses: 'Used in aromatherapy for its relaxing properties. It is also used topically in some traditional systems for its antiseptic and anti-inflammatory benefits.'
  },
  {
    id: 'chamomile',
    commonName: 'Chamomile',
    latinName: 'Matricaria chamomilla',
    description: 'A daisy-like plant commonly used to make a tea that promotes sleep and calms the nerves. It is also known to soothe stomach ailments.',
    therapeuticUses: ['Sleep Aid', 'Stress Relief', 'Digestive Health'],
    region: 'Europe and Western Asia',
    classification: 'Asteraceae family',
    imageSrc: 'https://images.unsplash.com/photo-1595594966682-998a44b79b5c?q=80&w=600&auto=format&fit=crop',
    imageHint: 'chamomile flowers tea',
    ayushUses: 'Often used in Unani and Western herbalism. It is a mild sedative, making it popular for insomnia and anxiety. It also helps with indigestion.'
  },
  {
    id: 'rosemary',
    commonName: 'Rosemary',
    latinName: 'Salvia rosmarinus',
    description: 'A fragrant evergreen herb with needle-like leaves. It is believed to improve memory and concentration and is rich in antioxidants.',
    therapeuticUses: ['Cognitive Function', 'Antioxidant', 'Anti-inflammatory'],
    region: 'Mediterranean',
    classification: 'Mint family',
    imageSrc: 'https://images.unsplash.com/photo-1598270591428-39b924c53846?q=80&w=600&auto=format&fit=crop',
    imageHint: 'rosemary sprigs',
    ayushUses: 'In traditional medicine, it is used to stimulate the mind, improve memory, and relieve muscle pain. The essential oil is used in aromatherapy for focus.'
  },
  {
    id: 'echinacea',
    commonName: 'Echinacea',
    latinName: 'Echinacea purpurea',
    description: 'Also known as purple coneflower, Echinacea is a popular herb believed to boost the immune system and help the body fight off infections, like the common cold.',
    therapeuticUses: ['Immunity Booster', 'Cold and Flu', 'Anti-inflammatory'],
    region: 'North America',
    classification: 'Asteraceae family',
    imageSrc: 'https://images.unsplash.com/photo-1594313490135-2c8a245a4a2c?q=80&w=600&auto=format&fit=crop',
    imageHint: 'purple coneflower',
    ayushUses: 'Though not native to India, it has been adopted into modern herbal practices for its immune-stimulating properties, similar to how Giloy is used in Ayurveda.'
  },
  {
    id: 'elderberry',
    commonName: 'Elderberry',
    latinName: 'Sambucus nigra',
    description: 'The dark purple berries of the elder tree are packed with antioxidants and vitamins. Syrups and extracts are often used to boost immunity and treat cold and flu symptoms.',
    therapeuticUses: ['Immunity Booster', 'Cold and Flu', 'Antioxidant'],
    region: 'Europe, North Africa, and Western Asia',
    classification: 'Adoxaceae family',
    imageSrc: 'https://images.unsplash.com/photo-1616118182928-86812835922a?q=80&w=600&auto=format&fit=crop',
    imageHint: 'elderberry bunch',
    ayushUses: 'Popular in Western herbalism, its use mirrors traditional remedies for viral infections. Rich in flavonoids, it is valued for its antiviral and immune-supporting effects.'
  },
  {
    id: 'marshmallow-root',
    commonName: 'Marshmallow Root',
    latinName: 'Althaea officinalis',
    description: 'This plant root has a high mucilage content, making it a soothing agent for sore throats, coughs, and digestive inflammation.',
    therapeuticUses: ['Sore Throat Relief', 'Digestive Health', 'Respiratory Health'],
    region: 'Europe, Western Asia, and North Africa',
    classification: 'Mallow family',
    imageSrc: 'https://images.unsplash.com/photo-1549887711-0a442a8a7e4b?q=80&w=600&auto=format&fit=crop&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageHint: 'marshmallow plant flower',
    ayushUses: 'Used for its demulcent (soothing) properties. It helps coat and protect mucous membranes in the throat and digestive tract, similar to licorice.'
  }
];


export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Which plant is known as the "elixir of life" in Ayurveda?',
    options: ['Ashwagandha', 'Tulsi (Holy Basil)', 'Turmeric', 'Amla'],
    correctAnswer: 'Tulsi (Holy Basil)',
    plantId: 'tulsi',
  },
  {
    id: 'q2',
    question: 'What is the primary active compound in Turmeric that gives it anti-inflammatory properties?',
    options: ['Gingerol', 'Piperine', 'Curcumin', 'Withanolides'],
    correctAnswer: 'Curcumin',
    plantId: 'turmeric',
  },
  {
    id: 'q3',
    question: 'Ashwagandha is best known for which of the following properties?',
    options: ['Stimulant', 'Diuretic', 'Adaptogen', 'Expectorant'],
    correctAnswer: 'Adaptogen',
    plantId: 'ashwagandha',
  },
  {
    id: 'q4',
    question: 'Which herb is often called a "brain tonic" and is used to enhance memory?',
    options: ['Brahmi', 'Giloy', 'Moringa', 'Licorice'],
    correctAnswer: 'Brahmi',
    plantId: 'brahmi',
  },
  {
    id: 'q5',
    question: 'Amla (Indian Gooseberry) is an extremely rich source of which vitamin?',
    options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'],
    correctAnswer: 'Vitamin C',
    plantId: 'amla',
  },
  {
    id: 'q6',
    question: 'The name of which herb translates to "she who possesses a hundred husbands" in Ayurveda?',
    options: ['Neem', 'Gotu Kola', 'Shatavari', 'Ginkgo Biloba'],
    correctAnswer: 'Shatavari',
    plantId: 'shatavari',
  },
  {
    id: 'q7',
    question: 'Which part of the Ginger plant is most commonly used as a spice and medicine?',
    options: ['Leaf', 'Flower', 'Stem', 'Rhizome (Root)'],
    correctAnswer: 'Rhizome (Root)',
    plantId: 'ginger',
  },
  {
    id: 'q8',
    question: 'The essential oil from which plant is known as the "oil of tranquility"?',
    options: ['Lemongrass', 'Eucalyptus', 'Vetiver', 'Sandalwood'],
    correctAnswer: 'Vetiver',
    plantId: 'vetiver',
  },
  {
    id: 'q9',
    question: 'Neem is well-known in traditional medicine for which primary benefit?',
    options: ['Boosting energy', 'Improving eyesight', 'Antibacterial and skin health', 'Enhancing flavor'],
    correctAnswer: 'Antibacterial and skin health',
    plantId: 'neem',
  },
  {
    id: 'q10',
    question: 'Which plant, often called the "miracle tree", is a powerhouse of nutrients?',
    options: ['Moringa', 'Cardamom', 'Fennel', 'Sandalwood'],
    correctAnswer: 'Moringa',
    plantId: 'moringa',
  },
  {
    id: 'q11',
    question: 'What is the main therapeutic use of Lavender essential oil?',
    options: ['Boosting energy', 'Aiding digestion', 'Reducing stress and promoting sleep', 'Improving memory'],
    correctAnswer: 'Reducing stress and promoting sleep',
    plantId: 'lavender',
  },
  {
    id: 'q12',
    question: 'Which flower, often made into a tea, is a popular remedy for insomnia?',
    options: ['Rose', 'Chamomile', 'Hibiscus', 'Jasmine'],
    correctAnswer: 'Chamomile',
    plantId: 'chamomile',
  },
  {
    id: 'q13',
    question: 'Rosemary is traditionally believed to help with what function?',
    options: ['Bone strength', 'Muscle growth', 'Memory and concentration', 'Blood purification'],
    correctAnswer: 'Memory and concentration',
    plantId: 'rosemary',
  },
  {
    id: 'q14',
    question: 'Echinacea, or purple coneflower, is most commonly used for what purpose?',
    options: ['Boosting the immune system', 'Soothing burns', 'Improving vision', 'Reducing cholesterol'],
    correctAnswer: 'Boosting the immune system',
    plantId: 'echinacea',
  },
  {
    id: 'q15',
    question: 'The high mucilage content of Marshmallow Root makes it effective for...',
    options: ['Soothing sore throats', 'Stimulating hair growth', 'Increasing appetite', 'Strengthening nails'],
    correctAnswer: 'Soothing sore throats',
    plantId: 'marshmallow-root',
  },
];

    